### ISSUE TITLE
need to be updated now(11/20/2018)

### ISSUE THREAD

**Issue by wilsonfly** [chinanf-boy/go-ipfs-zh#1]
some entries are missing comparing with [https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md).
0.0

**Comment by chinanf-boy** [comment]
I see, I see! May be later :)

**Comment by chinanf-boy** [comment]
@wilsonfly Done

update with commit hash https://github.com/ipfs/go-ipfs/tree/b7a48531b7b64fcaa858e2c28e42fb4eeb6fcc0d

**Comment by chinanf-boy** [comment]
中文? 如无问题，请自行关闭Issue, 谢谢🙏

**Comment by chinanf-boy** [comment]
@wilsonfly if ok, please close the Issue

**Comment by wilsonfly** [comment]
sorry for being late
thanks a lot, good job
